
function search() {
    var searchTerm = document.getElementById('searchInput').value;
    fetchDataFromServer(searchTerm);
}

function fetchDataFromServer(searchTerm) {
    var data = [
        { id: 1, name: 'Rose', Colour: 'Red,Pink,Blue,White,Yellow,etc.', Species: '360species', Aromatic: 'Yes', Use: 'Ornamental Plants,Cut Flowers,Perfume,Food and drink', BotanicalName: 'Rosa', Grewin: 'America, Europe, northwest Africa and many parts of Asia and Oceania.', description: 'Medicinal Purpose: It treats skin diseases, eye strain, stress, insomnia, diarrhea and hyperacidity  due to its medicinal properties <br>like anti-inflammatory, aphrodisiac, \n anti-depressant, astringent, antispasmodic, cleansing, anti- bacterial and antiseptic properties.', Image: './rose.jpg'},
        { id: 2, name: 'Lotus', Colour: 'Pink,Red,White,Purple.', Species: 'aroud 100 species', Aromatic: 'Yes', Use: ':- Cookiong,Baking,Adding flavour to beverages.', BotanicalName: 'Nelumbo nucifera', Grewin: 'Asia, and is widespread from Iran and the Caspian Sea eastwards to China and Japan,<br> and southeast wards to India and Indo-China, then to northern Australia.', description: 'Medicinal Purpose:- use  of  lotus for bleeding, cough, fever, liver and stomach problems, and other conditions, <br>but there is no scientific evidence to support these uses.', Image: './lotus.jpg' },
        { id: 3, name: 'Sunflower', Colour: 'Yellow and Black', Species: 'around 70', Aromatic: 'No', Use: 'cooking oil, meal and confectionary products.', BotanicalName: 'Helianthus annuus', Grewin: 'Russia, Ukraine, Argentina, Turkey and Romania', description: 'Medicinal Purpose:- Tender leaf petioles, seeds, and flowers are edible and <br>are used as an expectorant, diuretic and astringent. Tea made from the leaves <br>is reputed to help to reduce fever, and when made into a poultice, can be applied to sores, bug bites, and swellings.Oil from the <br>pressed seeds are high in vitamin E', Image: './sunflower.jpg'},
        { id: 4, name: 'Hibiscus', Colour: 'Yellow,Pink,Red,White,etc.', Species: 'around 100 species', Aromatic: 'No', Use: ':- Hibiscus dry flowers can be used in a variety of sweet and savory dishes, such as jellies, jams, syrups, and marinades. ', BotanicalName: 'Hibiscus panduriformis.', Grewin: 'West Africa, East Africa, Southeast Asia, or Northeastern India.', description: 'Medicinal Purpose:-  Hibiscus is used for treating loss of appetite, colds, heart and nerve diseases, upper respiratory <br>tract pain and swelling (inflammation), fluid retention, stomach irritation, and disorders of circulation; for dissolving phlegm;as a gentle <br> laxative; and as a diuretic to increase urine output.', Image: './hibiscus.jpg'},
        { id: 5, name: 'Marigold', Colour: 'Yellow,Orange,Red,etc.',Species: '50 species', Aromatic:'No', Use: ':-Ornamental Plants,Medicinal Purpose,Heal Wounds,Antioxidents,' ,BotanicalName:'Tagetes',Grewin:'Southwestern North America,tropical America,South America,India',description:'Medicinal Purpose:-Skin condiotions of all kinds, including contusions,bruises and varicose vein',Image: './Marigold.jpg'},
        { id: 6, name: 'Jasmine', Colour: 'Yellow,Orange,White.',Species: ' Around 200 species', Aromatic:'No', Use: ':-Ornamental Plants,Medicinal Purpose,Heal Wounds,Antioxidents,' ,BotanicalName:'Jasminum',Grewin:'Tropical and subtropical regions of Eurasia,Africa',description:'Medicinal Purpose:-Skin condiotions of all kinds, including contusions,bruises and varicose vein',Image: './jasmine.jpg'},
        { id: 7, name: 'Calendula',Colour:'Yellow,White,Pink', Species: '15-20 species', Aromatic:'Yes',Use: ':-The petals of calendula flower have been used historically to heal cuts, burns and wounds,also use in skin care products',BotanicalName:' pot marigold',Grewin:'Europe, Western Asia, and the United States', description:'Medicinal industry: -cosmatics products and healthcare products',Image: './calendula.jpg'},
        { id: 9, name: 'Disey',Colour:' White,Yellow,Pink', Species: '25-30 species', Aromatic:'Yes',Use: ':-They are also used in floral arrangements. Additionally, some herbal traditions attribute medicinal properties to certain parts of the plant.',BotanicalName:'Bellis perennis',Grewin:'Europe, North America', description:'Medicinal Purpose: - It uses wild daisy tea for coughs, bronchitis, disorders of the liver and kidneys, and swelling (inflammation).<br>Common daisies typically have low-growing rosettes of dark green, spoon-shaped leaves. The flowers rise above the foliage on slender stems, and each flower consists of numerous white (or pink) petals radiating from a yellow center.',Image: './Daisey.jpg'},
        { id: 10, name: 'Lavender',Colour:' Violet,Purple', Species: '47', Aromatic:'Yes',Use: ':- Lavender is sometimes used in culinary applications, especially in desserts and teas. However, it should be used sparingly as it can have a strong flavor.',BotanicalName:'Lavandula spp',Grewin:'Cape Verde and the Canary Islands,Europe,Northern and eastern Africa,Southwest Asia to India.', description:'Medicinal Purpose: -Lavender has been used traditionally for various medicinal purposes, including as a remedy for stress, anxiety, and sleep disorders<br> Lavender essential oil is popular in aromatherapy for its calming and relaxing properties.',Image: './lavender.jpg'},
        { id: 11, name: 'Cornflower',Colour:'Blue,Pink,Purple, and White', Species: '12-13 species', Aromatic:'No',Use: ':-Cornflowers are popular ornamental plants and are often grown in gardens for their attractive blooms<br>The flowers are commonly used in floral arrangements, adding a splash of color.',BotanicalName:'Centaurea cyanus',Grewin:'Germany', description:'Medicinal Purpose: - Cornflowers have been used in herbal medicine for various purposes, including soothing eye irritations.<br>Cornflowers are used as edible decorations in salads or desserts. The petals are sometimes used to add color to teas or infusions.',Image: './cornflower.jpg'},
        { id: 12, name: 'Chamomile',Colour:'White,Yellow', Species: '20 species', Aromatic:'Yes',Use: ':-Chamomile is popularly used to make herbal tea. The tea is known for its calming and soothing properties, making it a popular choice for relaxation and before bedtime.',BotanicalName:'Matricaria chamomilla',Grewin:'Europe, North America, Asia', description:'Medicinal Purpose: -traditionally used in herbal medicine for its anti-inflammatory and mild sedative effect.<br>Used in skincare products for its anti-inflammatory and skin-soothing properties.',Image: './chamomile.jpg'},
        { id: 14, name: 'Bluebell',Colour:'White,Yellow,Pink', Species: '11', Aromatic:'Yes',Use: ':-They are also used in floral arrangements. Additionally, some herbal traditions attribute medicinal properties to certain parts of the plant.',BotanicalName:'Bellis perennis',Grewin:'Europe, North America', description:'Medicinal Purpose: - It uses wild daisy tea for coughs, bronchitis, disorders of the liver and kidneys, and swelling (inflammation).<br>Common daisies typically have low-growing rosettes of dark green, spoon-shaped leaves. The flowers rise above the foliage on slender stems, and each flower consists of numerous white (or pink) petals radiating from a yellow center.',Image: './bluebell.jpg'},
        { id: 15, name: 'Daffodil',Colour:'Yellow,White', Species: '51 species', Aromatic:'Yes',Use: ':-Daffodils are popular ornamental flowers, commonly used in gardens, parks, and floral arrangements.<br> They are also sometimes used for naturalizing in grassy areas and are frequently associated with the arrival of spring. ',BotanicalName:'Narcissus',Grewin:'Spain and Portugal', description:'Medicinal Purpose: - All parts of the daffodil plant contain a substance called lycorine, which can be toxic if ingested. Iti s important to keep daffodils out of reach of pets and to exercise caution when handling them..',Image: './daffodil.jpg'},
        { id: 17, name: 'Freesia',Colour:'White, Yellow, Pink, Red', Species: '20 species', Aromatic:'Yes',Use: ':-Freesia plants have slender, arching stems that bear multiple trumpet-shaped flowers.',BotanicalName:'Freesia refracta',Grewin:'Kenya south to South Africa', description:'Medicinal Purpose: -people of southern Africa treat headaches with an infusion of the roots in warm water.<br>They also treat burns with an ointment made from the ash of the leaves.',Image: './fressiaa.jpg'},
        { id: 18, name: 'Orchid',Colour:'', Species: ' 28,000 species', Aromatic:'Yes',Use: ':- Orchids have cultural, decorative, and economic significance. They are highly sought after as ornamental plants and are commonly used in floral arrangements.<br>Some orchids are cultivated for the production of vanilla (from the Vanilla orchid) or for their use in traditional medicine.',BotanicalName:'Orchidaceae',Grewin:'America, northwest South America', description:'Medicinal Purpose: Among 36 species, nine taxa show wound healing properties, eight taxa are used in inflammatory conditions, six for cough and cold, five as tonic and aphrodisiac and eight for other uses such as constipation, gastritis, bleeding, tonsillitis and piles.',Image: './Orchid.jpg'},
        { id: 19, name: 'Yarrow',Colour:'white, yellow, pink, and shades of red.', Species: '13 species', Aromatic:'Yes',Use: ':- Some cultures use yarrow in cooking, often as a flavoring or spice. However, caution is advised, as excessive consumption can be toxic.<br>is a popular ornamental plant in gardens and landscapes. Its feathery leaves and clusters of flowers make it an attractive addition to borders and meadows.',BotanicalName:'Achillea millefolium',Grewin:'Europe, North America', description:'Medicinal Purpose: -Yarrow has a long history of medicinal use. It is believed to have anti-inflammatory, antispasmodic, and wound-healing properties.<br>It has been used in traditional medicine to treat various ailments, including digestive issues and skin conditions.',Image: './yarrow.jpg'},
        { id: 20, name: 'Gaura',Colour:'white and pink', Species: '20 species', Aromatic:'No',Use: ':- Gaura is primarily grown for its ornamental value. Its wispy, butterfly-like flowers and long, arching stems make it an attractive addition to gardens, borders, and containers.',BotanicalName:'Lindheimeri',Grewin:'South Asia,North America', description:'Medicinal Purpose: - Penstemon can be used to treat spider bites, reduce bleeding and healing burns as has been done by the Navajo of the Kayenta region.',Image: './gaura.jpg'},
        { id: 21, name: 'bird of Paradise',Colour:'orange, blue, and white', Species: '45 species', Aromatic:'No',Use: ':- The long-lasting flowers of Bird of Paradise make them suitable for cut flower arrangements.<br>It is popular for its unique and exotic appearance.',BotanicalName:'Strelitzia',Grewin:'South Africa', description:'Medicinal Purpose: - Alleviate Allergies and Reduce Odors.Thanks to their extraordinary ability to absorb harmful VOCs from the ai.',Image: './bopp.jpg'},
        { id: 22, name: 'Medinilla',Colour:'pink, purple, and red', Species: '400 species', Aromatic:'Yes',Use: ':-Medinilla plants are primarily grown as ornamental houseplants or in tropical gardens. They are appreciated for their vibrant and showy flowers.',BotanicalName:'Genus',Grewin:' Southeast Asia, Philippines, Borneo, Sulawesi.', description:'Medicinal Purpose: -  Medinilla, spp majority were utilized as the fruit to be consumed by pregnant women and also used as medicine for diarrhea, mouth sores, anti inflammatory, anti-cancer, and anti-bacterial.',Image: './mendinilaa.jpg'},





    
        // Add more flower data as needed
    ];

    var results = data.filter(item => item.name.toLowerCase().includes(searchTerm.toLowerCase()));
    displaySearchResults(results);
}

function displaySearchResults(results) {
    var resultsContainer = document.getElementById('searchResults');

    resultsContainer.innerHTML = '';

    if (results.length === 0) {
        resultsContainer.innerHTML = 'No results found. Check Spelling   ';
    } else {
        // Display each result with name, description, and image
        results.forEach(result => {
            var resultElement = document.createElement('div');
            resultElement.innerHTML = `
                <strong>Name:</strong> ${result.name}<br>
                <strong>Colour:</strong> ${result.Colour}<br>
                <strong>Species:</strong> ${result.Species}<br>
                <strong>Aromatic:</strong> ${result.Aromatic}<br>
                <strong>Use:</strong> ${result.Use}<br>
                <strong>BotanicalName:</strong> ${result.BotanicalName}<br>
                <strong>Grewin:</strong> ${result.Grewin}<br>
                <strong>Description:</strong> ${result.description}<br> 
                <Strong>Image</strong><br><img src="${result.Image}" alt="${result.name} Image" width="110" height="110">`;
            resultsContainer.appendChild(resultElement);
        });
    }
}
